--- #YAML:1.0
name:                Tk
version:             804.028501
abstract:            Tk - a Graphical User Interface Toolkit
license:             unrestricted
author:              
    - nick@ing-simmons.net (Nick Ing-Simmons)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Encode:                        0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
